---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart lightdm
  systemd:
    name: lightdm
    state: restarted

- name: reload sshd
  service:
    name: sshd
    state: reloaded
    enabled: yes

- name: update grub
  command: update-grub2