# docker-compose_v3_alpine_pgsql_latest.yaml

version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - /opt/docker/zabbix/volumes/zbx_env/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - /opt/docker/zabbix/volumes/zbx_env/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/docker/zabbix/volumes/zbx_env/export:/var/lib/zabbix/export:rw
   - /opt/docker/zabbix/volumes/zbx_env/modules:/var/lib/zabbix/modules:ro
   - /opt/docker/zabbix/volumes/zbx_env/enc:/var/lib/zabbix/enc:ro
   - /opt/docker/zabbix/volumes/zbx_env/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/docker/zabbix/volumes/zbx_env/mibs:/var/lib/zabbix/mibs:rot-key.pem:ro
  deploy:
   placement:
    constraints: [node.hostname == zabbix]
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - .env_db_pgsql
   - .env_srv
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  networks:
   zbx_net_backend:
    aliases:
    - zabbix-server
    - zabbix-server-pgsql
    - zabbix-server-alpine-pgsql
    - zabbix-server-pgsql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-proxy-sqlite3:
  image: zabbix/zabbix-proxy-sqlite3:alpine-5.0-latest
  ports:
    - target: 10051
      published: 10061
      mode: host
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - /opt/docker/zabbix/volumes/zbx_env/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/docker/zabbix/volumes/zbx_env/modules:/var/lib/zabbix/modules:ro
   - /opt/docker/zabbix/volumes/zbx_env/enc:/var/lib/zabbix/enc:ro
   - /opt/docker/zabbix/volumes/zbx_env/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/docker/zabbix/volumes/zbx_env/mibs:/var/lib/zabbix/mibs:ro
  deploy:
   placement:
    constraints: [node.hostname == zabbixproxy01]
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.3'
      memory: 256M
  env_file:
   - .env_prx
   - .env_prx_sqlite3
  networks:
   zbx_net_backend:
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with SQLite3 database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "sqlite3"
   com.zabbix.os: "alpine"

 zabbix-web-nginx-pgsql:
  #image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
  image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0.18
  ports:
   - "80:8080"
   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/docker/zabbix/volumes/zbx_env/nginx/certs:/etc/ssl/nginx:ro
   - /opt/docker/zabbix/volumes/zbx_env/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
   - /opt/docker/zabbix/volumes/zbx_env/modules/:/usr/share/zabbix/modules/:ro
  deploy:
   placement:
    constraints: [node.hostname == zabbix]
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - .env_db_pgsql
   - .env_web
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-5.0-latest
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/docker/zabbix/volumes/zbx_env/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - /opt/docker/zabbix/volumes/zbx_env/modules:/var/lib/zabbix/modules:ro
   - /opt/docker/zabbix/volumes/zbx_env/enc:/var/lib/zabbix/enc:ro
   - /opt/docker/zabbix/volumes/zbx_env/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - .env_agent
  networks:
   zbx_net_backend:
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

 postgres-server:
  image: timescale/timescaledb:1.7.4-pg12
  volumes:
    - /pgdata-prod:/var/lib/postgresql/data:rw
  deploy:
   placement:
    constraints: [node.hostname == zabbixproxy01]
   resources:
    limits:
      cpus: '0.70'
      memory: 5000M
    reservations:
      cpus: '0.5'
      memory: 5000M
  env_file:
   - .env_db_pgsql
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
networks:
  zbx_net_frontend:
    driver: overlay
    ipam:
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: overlay
    internal: true
    ipam:
      config:
      - subnet: 172.16.239.0/24

secrets:
  POSTGRES_USER:
    file: /opt/docker/zabbix/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: /opt/docker/zabbix/.POSTGRES_PASSWORD
