- name: Download Google Chrome
  get_url: 
    url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
    dest: /tmp

- name: Install Google Chrome
  apt:
    deb: '/tmp/google-chrome-stable_current_amd64.deb'
    state: present