- name: Get content
  uri: 
    url: '{{ base_url_rstudio }}'
    method: GET
    force_basic_auth: yes
    return_content: yes
  register: data

- set_fact:
    full_url: "{{ data.content | regex_search('https://download1.rstudio.org/electron/' ~ ansible_facts.distribution_release ~ '/amd64/rstudio-(\\S*)-amd64.deb') }}"

- name: download R Studio IDE
  get_url:
    url: "{{ full_url }}"
    dest: /tmp
    force_basic_auth: yes
    owner: root 
    mode: '0755'

- set_fact:
    file_name: '{{ full_url | basename }}'

- name: Install R Studio IDE
  apt: 
    deb: "/tmp/{{ file_name }}"