- name: Add GPG key Sublime Text
  get_url:
    url: 'https://download.sublimetext.com/sublimehq-pub.gpg'
    dest: /etc/apt/trusted.gpg.d
    mode: '0644'
    force: true

- name: Parsing GPG key Sublime Text
  shell: cat /etc/apt/trusted.gpg.d/sublimehq-pub.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/sublimehq-pub.gpg

- name: adding Sublime Text repository
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    state: present
    filename: sublime-text

- name: install Sublime Text
  apt:
    name: sublime-text
    state: present