- name: Verificar se existe AllowUsers
  shell: "grep -E '^AllowUsers' /etc/ssh/sshd_config"
  changed_when: False
  failed_when: False
  register: grep_allowusers_ssh

- name: "Adicionar '{{ allow_users_ssh }}' em AllowUsers"
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "\nAllowUsers {{ allow_users_ssh }}"
    insertafter: 'Subsystem'
    validate: '/usr/sbin/sshd -T -f %s'
  notify: reload sshd
  when: grep_allowusers_ssh.rc != 0

- name: "Setar '{{ allow_users_ssh }}' em AllowUsers"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers '
    line: 'AllowUsers {{ allow_users_ssh }}'
    validate: '/usr/sbin/sshd -T -f %s'
  notify: reload sshd
  when: grep_allowusers_ssh.rc == 0