- name: PROVISIONAMENTO WINDOWS
  hosts: "{{ deployLabWin }}"

  tasks:
    - name: Renomear "{{ deployLabWin }}" (Windows)
      win_hostname:
        name: "{{ deployLabWin }}"
      register: rename

    - import_tasks: ./installZabbixAgent/installZbxAgent.yaml
   
    - import_tasks: setOUWindows.yml

    - name: Ajustar boot G4 (Windows)
      win_shell: bcdedit /set '{bootmgr}' path \EFI\ubuntu\grubx64.efi
      when: deployLabWin is search("G4")      

    - name: Desativar AutoLogin (Windows)
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        data: 0
        type: string
        state: present

    - name: Ingressar "{{ deployLabWin }}" dominio (Windows)
      win_shell: |
        $domain = "windows.local.com"
        $username = 'local\ansible'
        $password = "{{ vault_domain }}" | ConvertTo-SecureString -asPlainText -Force 
        $credential = New-Object System.Management.Automation.PSCredential($username,$password)
        $ouPath = "{{ ou_path_windows }}"
        Sleep -s 10    
        Add-Computer -DomainName $domain -Credential $credential -OuPath $ouPath -Options JoinWithNewName,AccountCreate -Restart -Force
      async: 10
      poll: 0