- name: Get content
  win_uri: 
    url: https://portswigger.net/burp/releases/community/latest
    method: GET
    return_content: yes
  register: data

- debug: msg="{{ data.content | regex_search('([0-9]+(\.[0-9]+)+)') }}"
  register: burp_version

# - name: Latest version Burp Suite
#   set_fact:
#     burp_version: "{{ data.content | regex_search('([0-9]+(\\.[0-9]+)+)') }}"

# - debug: msg="{{base_url_burp}}{{burp_version}}&type=WindowsX64"

- name: Download Burp
  win_get_url:
    url: "{{base_url_burp}}{{burp_version.msg}}&type=WindowsX64"
    dest: C:\Users\Public\Desktop\Burp.exe

- name: Install Burp
  win_package:
    path: C:\Users\Public\Desktop\Burp.exe
    product_id: auto
    arguments: -q

- name: Remove installer
  win_file:
    path: C:\Users\Public\Desktop\Burp.exe
    state: absent

# - name: Create Shortcut Burp Suite
#   win_shortcut:
#     src: C:\Program Files\BurpSuiteCommunity\BurpSuiteCommunity.exe
#     dest: C:\Users\Public\Desktop\BurpSuiteCommunity.lnk
#     icon: C:\Program Files\BurpSuiteCommunity\BurpSuiteCommunity.exe,0